name: everettjf
description: iOS/Windows developer
meta_description: "everettjf - iOS/Windows developer"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://everettjf.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
author: 'everettjf'
email: everettjf@live.com

url: https://everettjf.github.io # the base hostname & protocol for your site
permalink:  /:year/:month/:day/:title

markdown:    kramdown
