name: everettjf
description: iOS/Windows Developer
meta_description: "everettjf - iOS/Windows Developer"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://everettjf.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
author: 'everettjf'
email: everettjf@live.com

url: https://everettjf.github.io # the base hostname & protocol for your site
permalink:  /:year/:month/:day/:title

markdown:    kramdown
