name: everettjf
description: 
meta_description: "everettjf"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://everettjf.github.io'
gems: [jekyll-paginate]

# Details for the RSS feed generator
author: 'everettjf'
email: everettjf@live.com

url: https://everettjf.github.io # the base hostname & protocol for your site
permalink:  /:year/:month/:day/:title

